
export interface BibleBook  {
  bookNumber: number;
  bookName: string;
  chapters: number;
}

export const bibleBooks: { [type: string]: BibleBook[] } = {
  'Altes Testament': [
    { bookNumber: 1, bookName: '01 - Genesis', chapters: 50 },
    { bookNumber: 2, bookName: '02 - Exodus', chapters: 40 },
    { bookNumber: 3, bookName: '03 - Levitikus', chapters: 27 },
    { bookNumber: 4, bookName: '04 - Numeri', chapters: 36 },
    { bookNumber: 5, bookName: '05 - Deuteronomium', chapters: 34 },
    { bookNumber: 6, bookName: '06 - Josua', chapters: 24 },
    { bookNumber: 7, bookName: '07 - Richter', chapters: 21 },
    { bookNumber: 8, bookName: '08 - Rut', chapters: 4 },
    { bookNumber: 9, bookName: '09 - 1. Samuel', chapters: 31 },
    { bookNumber: 10, bookName: '10 - 2. Samuel', chapters: 24 },
    { bookNumber: 11, bookName: '11 - 1. Könige', chapters: 22 },
    { bookNumber: 12, bookName: '12 - 2. Könige', chapters: 25 },
    { bookNumber: 13, bookName: '13 - 1. Chronik', chapters: 29 },
    { bookNumber: 14, bookName: '14 - 2. Chronik', chapters: 36 },
    { bookNumber: 15, bookName: '15 - Esra', chapters: 10 },
    { bookNumber: 16, bookName: '16 - Nehemia', chapters: 13 },
    { bookNumber: 17, bookName: '17 - Ester', chapters: 10 },
    { bookNumber: 18, bookName: '18 - Hiob', chapters: 42 },
    { bookNumber: 19, bookName: '19 - Psalmen', chapters: 150 },
    { bookNumber: 20, bookName: '20 - Sprüche', chapters: 31 },
    { bookNumber: 21, bookName: '21 - Prediger', chapters: 12 },
    { bookNumber: 22, bookName: '22 - Hoheslied', chapters: 8 },
    { bookNumber: 23, bookName: '23 - Jesaja', chapters: 66 },
    { bookNumber: 24, bookName: '24 - Jeremia', chapters: 52 },
    { bookNumber: 25, bookName: '25 - Klagelieder', chapters: 5 },
    { bookNumber: 26, bookName: '26 - Hesekiel', chapters: 48 },
    { bookNumber: 27, bookName: '27 - Daniel', chapters: 12 },
    { bookNumber: 28, bookName: '28 - Hosea', chapters: 14 },
    { bookNumber: 29, bookName: '29 - Joel', chapters: 4 },
    { bookNumber: 30, bookName: '30 - Amos', chapters: 9 },
    { bookNumber: 31, bookName: '31 - Obadja', chapters: 1 },
    { bookNumber: 32, bookName: '32 - Jona', chapters: 4 },
    { bookNumber: 33, bookName: '33 - Micha', chapters: 7 },
    { bookNumber: 34, bookName: '34 - Nahum', chapters: 3 },
    { bookNumber: 35, bookName: '35 - Habakuk', chapters: 3 },
    { bookNumber: 36, bookName: '36 - Zefanja', chapters: 3 },
    { bookNumber: 37, bookName: '37 - Haggai', chapters: 2 },
    { bookNumber: 38, bookName: '38 - Sacharja', chapters: 14 },
    { bookNumber: 39, bookName: '39 - Maleachi', chapters: 3 }
  ],
  'Neues Testament': [  
    { bookNumber: 50, bookName: '01 - Matthäus', chapters: 28 },
    { bookNumber: 51, bookName: '02 - Markus', chapters: 16 },
    { bookNumber: 52, bookName: '03 - Lukas', chapters: 24 },
    { bookNumber: 53, bookName: '04 - Johannes', chapters: 21 },
    { bookNumber: 54, bookName: '05 - Apostelgeschichte', chapters: 28 },
    { bookNumber: 55, bookName: '06 - Römer', chapters: 16 },
    { bookNumber: 56, bookName: '07 - 1. Korinther', chapters: 16 },
    { bookNumber: 57, bookName: '08 - 2. Korinther', chapters: 13 },
    { bookNumber: 58, bookName: '09 - Galater', chapters: 6 },
    { bookNumber: 59, bookName: '10 - Epheser', chapters: 6 },
    { bookNumber: 60, bookName: '11 - Philipper', chapters: 4 },
    { bookNumber: 61, bookName: '12 - Kolosser', chapters: 4 },
    { bookNumber: 62, bookName: '13 - 1. Thessalonicher', chapters: 5 },
    { bookNumber: 63, bookName: '14 - 2. Thessalonicher', chapters: 3 },
    { bookNumber: 64, bookName: '15 - 1. Timotheus', chapters: 6 },
    { bookNumber: 65, bookName: '16 - 2. Timotheus', chapters: 4 },
    { bookNumber: 66, bookName: '17 - Titus', chapters: 3 },
    { bookNumber: 67, bookName: '18 - Philemon', chapters: 1 },
    { bookNumber: 68, bookName: '19 - Hebräer', chapters: 13 },
    { bookNumber: 69, bookName: '20 - Jakobus', chapters: 5 },
    { bookNumber: 70, bookName: '21 - 1. Petrus', chapters: 5 },
    { bookNumber: 71, bookName: '22 - 2. Petrus', chapters: 3 },
    { bookNumber: 72, bookName: '23 - 1. Johannes', chapters: 5 },
    { bookNumber: 73, bookName: '24 - 2. Johannes', chapters: 1 },
    { bookNumber: 74, bookName: '25 - 3. Johannes', chapters: 1 },
    { bookNumber: 75, bookName: '26 - Judas', chapters: 1 },
    { bookNumber: 76, bookName: '27 - Offenbarung', chapters: 22 },
  ],
  'Apokryphen': [
    { bookNumber: 40, bookName: '01 - Judit', chapters: 16 },
    { bookNumber: 41, bookName: '02 - Weisheit', chapters: 19 },
    { bookNumber: 42, bookName: '03 - Tobit', chapters: 14 },
    { bookNumber: 43, bookName: '04 - Sirach', chapters: 51 },
    { bookNumber: 44, bookName: '05 - Baruch', chapters: 5 },
    { bookNumber: 83, bookName: '06 - Brief Jeremias', chapters: 1 },
    { bookNumber: 45, bookName: '07 - 1. Makkabäer', chapters: 16 },
    { bookNumber: 46, bookName: '08 - 2. Makkabäer', chapters: 15 },
    { bookNumber: 47, bookName: '09 - Zusätze Ester', chapters: 7 },
    { bookNumber: 48, bookName: '10 - Zusätze Daniel', chapters: 3 },
    { bookNumber: 49, bookName: '11 - Gebet Manasses', chapters: 1 },
  ]
};
