
export interface BibleBook  {
  bookNumber: number;
  bookName: string;
  chapters: number;
}

export const bibleBooks: { [type: string]: BibleBook[] } = {
  'at': [
    { bookNumber: 1,  bookName: 'Genesis', chapters: 50 },
    { bookNumber: 2,  bookName: 'Exodus', chapters: 40 },
    { bookNumber: 3,  bookName: 'Levitikus', chapters: 27 },
    { bookNumber: 4,  bookName: 'Numeri', chapters: 36 },
    { bookNumber: 5,  bookName: 'Deuteronomium', chapters: 34 },
    { bookNumber: 6,  bookName: 'Josua', chapters: 24 },
    { bookNumber: 7,  bookName: 'Richter', chapters: 21 },
    { bookNumber: 8,  bookName: 'Ruth', chapters: 4 },
    { bookNumber: 9,  bookName: '1. Samuel', chapters: 31 },
    { bookNumber: 10, bookName: '2. Samuel', chapters: 24 },
    { bookNumber: 11, bookName: '1. Könige', chapters: 22 },
    { bookNumber: 12, bookName: '2. Könige', chapters: 25 },
    { bookNumber: 13, bookName: '1. Chronik', chapters: 29 },
    { bookNumber: 14, bookName: '2. Chronik', chapters: 36 },
    { bookNumber: 15, bookName: 'Esra', chapters: 10 },
    { bookNumber: 16, bookName: 'Nehemia', chapters: 13 },
    { bookNumber: 17, bookName: 'Esther', chapters: 10 },
    { bookNumber: 18, bookName: 'Hiob', chapters: 42 },
    { bookNumber: 19, bookName: 'Psalmen', chapters: 150 },
    { bookNumber: 20, bookName: 'Sprüche', chapters: 31 },
    { bookNumber: 21, bookName: 'Prediger', chapters: 12 },
    { bookNumber: 22, bookName: 'Hoheslied', chapters: 8 },
    { bookNumber: 23, bookName: 'Jesaja', chapters: 66 },
    { bookNumber: 24, bookName: 'Jeremia', chapters: 52 },
    { bookNumber: 25, bookName: 'Klagelieder', chapters: 5 },
    { bookNumber: 26, bookName: 'Hesekiel', chapters: 48 },
    { bookNumber: 27, bookName: 'Daniel', chapters: 12 },
    { bookNumber: 28, bookName: 'Hosea', chapters: 14 },
    { bookNumber: 29, bookName: 'Joel', chapters: 4 },
    { bookNumber: 30, bookName: 'Amos', chapters: 9 },
    { bookNumber: 31, bookName: 'Obadja', chapters: 1 },
    { bookNumber: 32, bookName: 'Jona', chapters: 4 },
    { bookNumber: 33, bookName: 'Micha', chapters: 7 },
    { bookNumber: 34, bookName: 'Nahum', chapters: 3 },
    { bookNumber: 35, bookName: 'Habakuk', chapters: 3 },
    { bookNumber: 36, bookName: 'Zefanja', chapters: 3 },
    { bookNumber: 37, bookName: 'Haggai', chapters: 2 },
    { bookNumber: 38, bookName: 'Sacharja', chapters: 14 },
    { bookNumber: 39, bookName: 'Maleachi', chapters: 3 }
  ],
  'nt': [  
    { bookNumber: 50, bookName: 'Matthäus', chapters: 28 },
    { bookNumber: 51, bookName: 'Markus', chapters: 16 },
    { bookNumber: 52, bookName: 'Lukas', chapters: 24 },
    { bookNumber: 53, bookName: 'Johannes', chapters: 21 },
    { bookNumber: 54, bookName: 'Apostelgeschichte', chapters: 28 },
    { bookNumber: 55, bookName: 'Römer', chapters: 16 },
    { bookNumber: 56, bookName: '1. Korinther', chapters: 16 },
    { bookNumber: 57, bookName: '2. Korinther', chapters: 13 },
    { bookNumber: 58, bookName: 'Galater', chapters: 6 },
    { bookNumber: 59, bookName: 'Epheser', chapters: 6 },
    { bookNumber: 60, bookName: 'Philipper', chapters: 4 },
    { bookNumber: 61, bookName: 'Kolosser', chapters: 4 },
    { bookNumber: 62, bookName: '1. Thessalonicher', chapters: 5 },
    { bookNumber: 63, bookName: '2. Thessalonicher', chapters: 3 },
    { bookNumber: 64, bookName: '1. Timotheus', chapters: 6 },
    { bookNumber: 65, bookName: '2. Timotheus', chapters: 4 },
    { bookNumber: 66, bookName: 'Titus', chapters: 3 },
    { bookNumber: 67, bookName: 'Philemon', chapters: 1 },
    { bookNumber: 68, bookName: 'Hebräer', chapters: 13 },
    { bookNumber: 69, bookName: 'Jakobus', chapters: 5 },
    { bookNumber: 70, bookName: '1. Petrus', chapters: 5 },
    { bookNumber: 71, bookName: '2. Petrus', chapters: 3 },
    { bookNumber: 72, bookName: '1. Johannes', chapters: 5 },
    { bookNumber: 73, bookName: '2. Johannes', chapters: 1 },
    { bookNumber: 74, bookName: '3. Johannes', chapters: 1 },
    { bookNumber: 75, bookName: 'Judas', chapters: 1 },
    { bookNumber: 76, bookName: 'Offenbarung', chapters: 22 },
  ],
  'apo': [
    { bookNumber: 80, bookName: 'Tobit', chapters: 14 },
    { bookNumber: 81, bookName: 'Judit', chapters: 16 },
    { bookNumber: 82, bookName: '1. Makkabäer', chapters: 16 },
    { bookNumber: 83, bookName: '2. Makkabäer', chapters: 15 },
    { bookNumber: 84, bookName: 'Weisheit', chapters: 19 },    
    { bookNumber: 85, bookName: 'Jesus Sirach', chapters: 51 },
    { bookNumber: 86, bookName: 'Baruch', chapters: 5 },
    { bookNumber: 87, bookName: 'Brief Jeremias', chapters: 1 },
    { bookNumber: 88, bookName: 'Zusätze Esther', chapters: 7 },
    { bookNumber: 89, bookName: 'Zusätze Daniel', chapters: 3 },
    { bookNumber: 90, bookName: 'Gebet Manasses', chapters: 1 },
  ]
};
